removed treeCount because of error
edu/cs300/ParallelTextSearch.java:91: error: variable declaration not allowed here
          MessageJNI message =  new MessageJNI().writeLongestWordResponseMsg(0, prefix, counter, "/home/ecjackson5/Spring_cs300_project/"+fileList.get(counter), results, treeCount, 0);
                     ^
edu/cs300/ParallelTextSearch.java:93: error: variable declaration not allowed here
          MessageJNI message =  new MessageJNI().writeLongestWordResponseMsg(0, prefix, counter, "/home/ecjackson5/Spring_cs300_project/"+fileList.get(counter), results, treeCount, 1);